pipeline:
    name: test000
    identifier: test000
    projectIdentifier: dougproject
    orgIdentifier: default
    storeType: REMOTE
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.CItestK8sConnectorU4hsfzj5Q7
                          namespace: harness-qa-delegate
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: push-to-dockerhub
                                identifier: pushtodockerhub
                                spec:
                                    connectorRef: dbothwelldockerhub
                                    repo: dbothwell/sgetestone
                                    tags:
                                        - sgetestone-master-latest
                                        - <+trigger.branch>
    properties:
        ci:
            codebase:
                connectorRef: douglasjbothwellgithub
                repoName: " sgeTestOne"
                build: <+input>
